### ISSUE TITLE
fix facebook hr module

### ISSUE THREAD

**Issue by FadiZahhar** [FadiZahhar/yamenest#39]
-phone number
-adding " Experience" to Years of

**Comment by FadiZahhar** [comment]
I'm working on it, today should be done and will close the issue.

**Comment by rehamelirani** [comment]
Hello,

it is still the same.

Best,


*Reham El IraniConstruction Manager & ISO9001 Internal Auditor*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by FadiZahhar** [comment]
I fix it , to see the changes on the facebook application , right click the mouse and click reload page. then you will see the changes, this issue is closed. Regards,

**Comment by rehamelirani** [comment]
Dear Fadi,

The problems are still not fixed.

[image: Inline image 1]

Best,


*Reham El IraniConstruction Manager & ISO9001 Internal Auditor*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>
